services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: messenger-php
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable
    container_name: messenger-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: messenger-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger
      MYSQL_USER: messenger
      MYSQL_PASSWORD: messenger
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: messenger-redis
    ports:
      - "6379:6379"

  websocket:
    image: node:18
    working_dir: /app
    container_name: messenger-ws
    volumes:
      - ./ws:/app
    command: [ "/bin/sh", "-c", "npm install && node server.js" ]

    ports:
      - "8081:8081"
    depends_on:
      - app

volumes:
  db_data:
